## Homework 2
### Anna McClimon, October 4th, 2026

In [1]:
import pandas as pd
import json
from IPython.display import display

### Question 1
Load the gun violence data set (gun-violence-data_01-2013_03-2018.csv) into a
DataFrame.

Question 1a. Use the appropriate command to report the data type for each column

In [2]:
# load gun violence data
gun_violence = pd.read_csv("gun-violence-data_01-2013_03-2018.csv", low_memory=False)

In [3]:
# report data types
print("Gun violence column data types:")
print(gun_violence.dtypes)

Gun violence column data types:
incident_id                      int64
date                            object
state                           object
city_or_county                  object
address                         object
n_killed                         int64
n_injured                        int64
incident_url                    object
source_url                      object
incident_url_fields_missing       bool
congressional_district         float64
gun_stolen                      object
gun_type                        object
incident_characteristics        object
latitude                       float64
location_description            object
longitude                      float64
n_guns_involved                float64
notes                           object
participant_age                 object
participant_age_group           object
participant_gender              object
participant_name                object
participant_relationship        object
participant_status              object
participant_type                object
sources                         object
state_house_district           float64
state_senate_district          float64
dtype: object

Question 1b. Filter the original data frame to show incidents that occurred in Iowa City, IA. Be
sure to not include incidents that occurred in Iowa City, CA. Save results to a new
data frame named iowa_city_ia. How many incidents occurred in Iowa City,
IA? Show the new data frame.

In [4]:
# save incidents in Iowa City and report count/display 
iowa_city_ia = gun_violence[(gun_violence["state"] == "Iowa") & (gun_violence["city_or_county"] == "Iowa City")].copy()
print("Number of incidents in Iowa City, IA:", len(iowa_city_ia))
display(iowa_city_ia)

Number of incidents in Iowa City, IA: 67

,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_url,source_url,incident_url_fields_missing,...,participant_age,participant_age_group,participant_gender,participant_name,participant_relationship,participant_status,participant_type,sources,state_house_district,state_senate_district
464,93491,2014-01-01,Iowa,Iowa City,backseat of victim's car,0,1,http://www.gunviolencearchive.org/incident/93491,http://thegazette.com/2014/01/06/iowa-city-pol...,False,...,1::35,0::Adult 18+||1::Adult 18+,0::Female||1::Female,1::Laticia T. Robinson,NaN,0::Injured||1::Unharmed,0::Victim||1::Subject-Suspect,http://thegazette.com/2014/01/06/iowa-city-pol...,85.0,43.0
1004,93495,2014-01-05,Iowa,Iowa City,1416 Plum St,0,0,http://www.gunviolencearchive.org/incident/93495,http://thegazette.com/2014/01/06/attempted-rob...,False,...,NaN,0::Adult 18+||1::Adult 18+||2::Adult 18+,0::Female||1::Male||2::Male,NaN,NaN,0::Unharmed||1::Unharmed||2::Unharmed,0::Victim||1::Subject-Suspect||2::Subject-Suspect,http://thegazette.com/2014/01/06/attempted-rob...,86.0,43.0
8427,113057,2014-03-07,Iowa,Iowa City,2600 block of Bartelt Road,0,1,http://www.gunviolencearchive.org/incident/113057,http://www.kcrg.com/news/crime/Police-More-Tha...,False,...,0:18|1:20|2:19|3:19|4:20,0:Adult 18+,0:Female|1:Male|2:Male|3:Male|4:Male,0:Denisha Davis|1:Devasier Dungtion|2:Gage Rup...,NaN,0:Injured|1:Unharmed|2:Unharmed|3:Unharmed|4:U...,0:Victim|1:Subject-Suspect|2:Subject-Suspect|3...,http://thegazette.com/2014/03/16/iowa-city-sho...,74.0,37.0
11780,122662,2014-04-04,Iowa,Iowa City,2600 Bartelt Road,0,1,http://www.gunviolencearchive.org/incident/122662,http://thegazette.com/2014/03/09/iowa-city-pol...,False,...,NaN,0::Adult 18+,0::Female,NaN,NaN,0::Injured,0::Victim,http://thegazette.com/2014/03/09/iowa-city-pol...,74.0,37.0
14054,127527,2014-04-21,Iowa,Iowa City,2626 Bartelt Road,0,0,http://www.gunviolencearchive.org/incident/127527,http://www.kcrg.com/news/crime/Iowa-City-Polic...,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.kcrg.com/news/crime/Iowa-City-Polic...,74.0,37.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216318,977802,2017-10-31,Iowa,Iowa City,400 S Johnson St,0,0,http://www.gunviolencearchive.org/incident/977802,http://www.thegazette.com/subject/news/public-...,False,...,0::19,0::Adult 18+,0::Male,0::Bret P Eldridge,NaN,"0::Unharmed, Arrested",0::Subject-Suspect,http://www.thegazette.com/subject/news/public-...,NaN,NaN
218072,986569,2017-11-11,Iowa,Iowa City,100 S. Linn St,0,0,http://www.gunviolencearchive.org/incident/986569,http://www.kcrg.com/content/news/University-of...,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.kcrg.com/content/news/University-of...,85.0,43.0
221829,1001368,2017-12-04,Iowa,Iowa City,Lakeside Dr and Amber Ln,0,0,http://www.gunviolencearchive.org/incident/100...,http://www.thegazette.com/subject/news/public-...,False,...,0::18||2::24||3::20,0::Adult 18+||2::Adult 18+||3::Adult 18+,0::Male||1::Male||2::Male||3::Male,0::Victor B Jones||1::Daivon D Jones||2::Dimio...,NaN,"0::Unharmed, Arrested||1::Unharmed, Arrested||...",0::Subject-Suspect||1::Subject-Suspect||2::Sub...,http://www.thegazette.com/subject/news/public-...,NaN,NaN
222739,1005517,2017-12-10,Iowa,Iowa City,Prairie du Chien Rd NE and 320th St NE,0,1,http://www.gunviolencearchive.org/incident/100...,http://www.thegazette.com/subject/news/public-...,False,...,0::11||1::13,0::Child 0-11||1::Teen 12-17,0::Male||1::Male,NaN,NaN,0::Injured||1::Unharmed,0::Victim||1::Subject-Suspect,http://whotv.com/2017/12/11/iowa-dnr-three-peo...,73.0,37.0
225266,1015778,2017-12-27,Iowa,Iowa City,Tracy Ln and Taylor Dr,0,0,http://www.gunviolencearchive.org/incident/101...,http://www.kwwl.com/story/37146795/2017/12/27/...,False,...,0::24,0::Adult 18+,0::Male,0::Shamari Smith,NaN,"0::Unharmed, Arrested",0::Subject-Suspect,http://www.kwwl.com/story/37146795/2017/12/27/...,86.0,43.0

Question 1c. Filter the original data frame to show incidents that occurred in both Iowa City
(like step b) and Cedar Rapids, IA. Be sure not to include Cedar Rapids, NE. Save
results to a new data frame named corridor_ia. How many incidents
occurred in Iowa City and Cedar Rapids, IA? Show the new data frame

In [5]:
# save incidents in IC and CR to corridor_ia, show df
corridor_ia = gun_violence[(gun_violence["state"] == "Iowa") & (gun_violence["city_or_county"].isin(["Iowa City", "Cedar Rapids"]))].copy()
print("Number of incidents in Iowa City and Cedar Rapids, IA:", len(corridor_ia))
display(corridor_ia)

Number of incidents in Iowa City and Cedar Rapids, IA: 306

,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_url,source_url,incident_url_fields_missing,...,participant_age,participant_age_group,participant_gender,participant_name,participant_relationship,participant_status,participant_type,sources,state_house_district,state_senate_district
464,93491,2014-01-01,Iowa,Iowa City,backseat of victim's car,0,1,http://www.gunviolencearchive.org/incident/93491,http://thegazette.com/2014/01/06/iowa-city-pol...,False,...,1::35,0::Adult 18+||1::Adult 18+,0::Female||1::Female,1::Laticia T. Robinson,NaN,0::Injured||1::Unharmed,0::Victim||1::Subject-Suspect,http://thegazette.com/2014/01/06/iowa-city-pol...,85.0,43.0
728,92650,2014-01-03,Iowa,Cedar Rapids,5620 Johnson Ave. NW,0,1,http://www.gunviolencearchive.org/incident/92650,http://thegazette.com/2014/01/08/teen-charged-...,False,...,0::21||1::19,0::Adult 18+||1::Adult 18+,0::Male||1::Female,0::Garret Chmelicek||1::Mariah L. Sprous,NaN,0::Injured||1::Unharmed,0::Victim||1::Subject-Suspect,http://thegazette.com/2014/01/03/overnight-sho...,70.0,35.0
1004,93495,2014-01-05,Iowa,Iowa City,1416 Plum St,0,0,http://www.gunviolencearchive.org/incident/93495,http://thegazette.com/2014/01/06/attempted-rob...,False,...,NaN,0::Adult 18+||1::Adult 18+||2::Adult 18+,0::Female||1::Male||2::Male,NaN,NaN,0::Unharmed||1::Unharmed||2::Unharmed,0::Victim||1::Subject-Suspect||2::Subject-Suspect,http://thegazette.com/2014/01/06/attempted-rob...,86.0,43.0
2156,96324,2014-01-14,Iowa,Cedar Rapids,4000 block of Wilson Av,0,0,http://www.gunviolencearchive.org/incident/96324,http://www.kcrg.com/news/crime/Cedar-Rapids-Po...,False,...,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+,0::Male||1::Male||2::Male,NaN,NaN,0::Unharmed||1::Unharmed||2::Unharmed,0::Victim||1::Subject-Suspect||2::Subject-Suspect,http://www.kcrg.com/news/crime/Cedar-Rapids-Po...,69.0,35.0
4518,200320,2014-01-30,Iowa,Cedar Rapids,3515 Banar Drive SW,3,0,http://www.gunviolencearchive.org/incident/200320,http://www.kwwl.com/story/24588260/2014/01/30/...,False,...,0::41||1::73||2::47,0::Adult 18+||1::Adult 18+||2::Adult 18+,0::Female||1::Female||2::Male,0::Ingrid Huber Livingston||1::Linda Jane Hube...,NaN,0::Killed||1::Killed||2::Killed,0::Victim||1::Victim||2::Subject-Suspect,http://www.kwwl.com/story/24588260/2014/01/30/...,69.0,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230278,1037698,2018-01-28,Iowa,Cedar Rapids,217 3rd St SE,0,1,http://www.gunviolencearchive.org/incident/103...,http://www.kcrg.com/content/news/Man-wanted-fo...,False,...,0::23||1::21,0::Adult 18+||1::Adult 18+,0::Male||1::Male,0::Michael Hodges||1::Zevon Johnson,NaN,"0::Injured, Arrested||1::Unharmed, Arrested",0::Victim||1::Subject-Suspect,http://www.thegazette.com/subject/news/public-...,69.0,35.0
232186,1055136,2018-02-10,Iowa,Cedar Rapids,NaN,0,1,http://www.gunviolencearchive.org/incident/105...,http://www.thegazette.com/subject/news/public-...,False,...,NaN,0::Adult 18+||1::Adult 18+||2::Adult 18+,0::Female||1::Male,2::Gage F Skola,NaN,0::Injured||1::Unharmed,0::Victim||1::Victim||2::Subject-Suspect,http://www.thegazette.com/subject/news/public-...,65.0,33.0
237180,1071075,2018-03-15,Iowa,Cedar Rapids,2125 Westdale Dr SW,0,1,http://www.gunviolencearchive.org/incident/107...,http://www.thegazette.com/subject/news/public-...,False,...,0::32||1::28,0::Adult 18+||1::Adult 18+,0::Male||1::Male,0::Isaac Chatman||1::Kent T Stevens,NaN,"0::Injured||1::Unharmed, Arrested",0::Victim||1::Subject-Suspect,http://www.thegazette.com/subject/news/public-...,69.0,35.0
237794,1073486,2018-03-19,Iowa,Cedar Rapids,639 40th St SE,1,1,http://www.gunviolencearchive.org/incident/107...,http://cbs2iowa.com/news/local/names-released-...,False,...,0::35||1::30,0::Adult 18+||1::Adult 18+,0::Male||1::Male,0::Brandon Toepfer||1::Kristopher Booker,NaN,0::Injured||1::Killed,0::Victim||1::Subject-Suspect,http://www.kcrg.com/content/news/Authorities-r...,65.0,33.0
238738,1077808,2018-03-25,Iowa,Cedar Rapids,3000 J St SW,0,0,http://www.gunviolencearchive.org/incident/107...,http://www.kwwl.com/story/37804757/2018/03/Sun...,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.kwwl.com/story/37804757/2018/03/Sun...,65.0,33.0

Question 1d. Save all Iowa incidents into a new data frame named iowa_df and save it as a
JSON file named iowa_incidents.json. Verify the created JSON file is valid
using https://jsonlint.com. Do not submit a copy of your JSON file, just the
working python code to create the file. We will validate it during grading.

In [6]:
# save all IA incidents in iowa_df and export iowa_incidents.json
iowa_df = gun_violence[gun_violence["state"] == "Iowa"].copy()
iowa_df.to_json("iowa_incidents.json", orient="records", indent=4)

# reopen the export to check its JSON syntax.
with open("iowa_incidents.json", "r", encoding="utf-8") as json_file:
    iowa_incidents = json.load(json_file)
print("Created valid JSON file: iowa_incidents.json")
print("Number of Iowa incidents exported:", len(iowa_incidents))

Created valid JSON file: iowa_incidents.json
Number of Iowa incidents exported: 2517

Question 1e. In 2016, which cities and states had the most fatalities? Display the maximum
number killed in 2016. Show n_killed, city_or_county, and state columns for
records that match the maximum number killed.

In [8]:
# parse dates separately to preserve the original df
incident_dates = pd.to_datetime(gun_violence["date"])
incidents_2016 = gun_violence[incident_dates.dt.year == 2016]
city_fatalities = incidents_2016.groupby(
    ["city_or_county", "state"], as_index=False
)["n_killed"].sum()
max_killed_2016 = city_fatalities["n_killed"].max()
print("max fatalities 2016:", max_killed_2016)
display(city_fatalities.loc[
    city_fatalities["n_killed"] == max_killed_2016,
    ["n_killed", "city_or_county", "state"]
])

max fatalities 2016: 591

      n_killed city_or_county     state
1303       591        Chicago  Illinois

### Question 2
Load the FIFA 21 complete player data set (players_21.csv) into a data frame named fifa_21.

In [9]:
# load data in fifa_21
fifa_21 = pd.read_csv("players_21.csv", low_memory=False)

Question 2a. Subset the following player IDs (sofifa_id) into a separate data frame named
selected_players. Save only the player id and long name fields into this new
data frame.

In [10]:
# subset ids into selected_players and display
player_ids = [231747, 153079, 162835, 200104, 223848, 208421]
selected_players = fifa_21.loc[fifa_21["sofifa_id"].isin(player_ids), ["sofifa_id", "long_name"]].copy()
display(selected_players)

     sofifa_id                          long_name
6       231747               Kylian Mbappé Lottin
13      153079  Sergio Leonel Agüero del Castillo
23      162835                   Samir Handanovič
46      200104                            손흥민 孙兴慜
70      223848            Sergej Milinković-Savić
112     208421               Saúl Ñíguez Esclápez

Question 2b. Subset players with a height greater than or equal to 191cm and a weight greater
than or equal to 90kg into a separate data frame named big_players. Display
the number of players in this new data frame.

In [15]:
# save players at least 191 cm and 90 kg in big_players 
big_players = fifa_21[(fifa_21["height_cm"] >= 191) & (fifa_21["weight_kg"] >= 90)].copy()
print("Players at least 191 cm tall and 90 kg:", len(big_players))

Players at least 191 cm tall and 90 kg: 355

Question 2c. What is the age of the oldest player(s)? The youngest? What is the median age
and the mean age of all players. Store each in variables and display them. Display
results in whole numbers.

In [16]:
# store and display the oldest, youngest, median, and mean ages then display
oldest_age = fifa_21["age"].max()
youngest_age = fifa_21["age"].min()
median_age = fifa_21["age"].median()
mean_age = fifa_21["age"].mean()
print(f"Oldest player age: {oldest_age:.0f} years")
print(f"Youngest player age: {youngest_age:.0f} years")
print(f"Median player age: {median_age:.0f} years")
print(f"Mean player age: {mean_age:.0f} years")

Oldest player age: 53 years
Youngest player age: 16 years
Median player age: 25 years
Mean player age: 25 years

Question 2d. Show the long name, age, and height for the oldest player(s) who prefer their left
foot

In [17]:
# show long name, age, and height for the oldest players who are lefties
left_footed_players = fifa_21[fifa_21["preferred_foot"] == "Left"].copy()
oldest_left_age = left_footed_players["age"].max()
oldest_left_players = left_footed_players.loc[left_footed_players["age"] == oldest_left_age, ["long_name", "age", "height_cm"]].copy()
print("Oldest left-footed players (height in cm):")
display(oldest_left_players)

Oldest left-footed players (height in cm):

                                long_name  age  height_cm
11701  Hussein Omar Abdul Ghani Sulaimani   43        173

Question 2e. Display the number of athletes and the number of columns in this data set

In [18]:
# display atheltes and columns
number_of_athletes, number_of_columns = fifa_21.shape
print("Number of athletes in FIFA 21:", number_of_athletes)
print("Number of columns in FIFA 21:", number_of_columns)

Number of athletes in FIFA 21: 18944
Number of columns in FIFA 21: 106